# Docker compose file for local development

version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    env_file: .env

  backend-migrate:
    build: .
    entrypoint: ["alembic", "upgrade", "head"]
    env_file: .env

  postgres:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    image: groonga/pgroonga:3.1.7-debian-16
    env_file: .env
    volumes:
      - ".local/postgres:/var/lib/postgresql/data"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    env_file:
      - .env
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command:
      - start-dev
      - --db
      - postgres
      - --db-url
      - jdbc:postgresql://${KEYCLOAK_DATABASE_HOST}/${KEYCLOAK_DATABASE_NAME}
      - --db-username
      - ${KEYCLOAK_DATABASE_USERNAME}
      - --db-password
      - ${KEYCLOAK_DATABASE_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
