# Docker compose file for local development

version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    env_file: .env

  backend-migrate:
    build: .
    entrypoint: ["alembic", "upgrade", "head"]
    env_file: .env

  postgres:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    image: groonga/pgroonga:3.1.7-debian-16
    env_file: .env
    volumes:
      - ".local/postgres:/var/lib/postgresql/data"
