image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""
podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

migrations:
  enabled: true
  command: ["alembic", "upgrade", "head"]
  resources: {}

api:
  enabled: true
  port: 8000
  args: []
  replicaCount: 3
  probePath: /health
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCpuUtilization: 80
  antiAffinity:
    enable: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 256Mi

  tmpfs:
    enabled: false
    sizeLimit: 1Gi

  ingress:
    enabled: true
    className: "nginx"
    annotations: {}
    host: ""
    path: /
    pathType: Prefix
    tls: []

  service:
    type: ClusterIP

imageResizer:
  replicaCount: 1
  entrypoint:
    - "python"
    - "-m"
    - "app.adapters.image_resizer"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 256Mi

cronjobs:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi
  tasks: {}
#    task-name:
#      schedule: "* * * * *"
#      entrypoint: ["python", "-m", "package.module"]
#    task-name1:
#      schedule: "* * * * *"
#      suspended: true
#      entrypoint: ["python", "-m", "package.module"]

commonEnvFrom: []
imagePullSecrets: []
