"""
Add user avatar

Revision ID: 88202356116f
Revises: e31103f7d3e4
Create Date: 2024-04-20 03:46:43.536805

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "88202356116f"
down_revision: str | None = "e31103f7d3e4"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("avatar_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_user_avatar_id_image_set"),
        "user",
        "image_set",
        ["avatar_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_avatar_id_image_set"),
        "user",
        type_="foreignkey",
    )
    op.drop_column("user", "avatar_id")
    # ### end Alembic commands ###
